title: Logic@GU
author: G.E. Leigh
email: graham.leigh@gu.se
description: > # this means to ignore newlines until "baseurl:"
  Homepage of the Logic Group at the University of Gothenburg.

tagline: The logic group at the University of Gothenburg


baseurl: "/"
# theme: jekyll-theme-slate

timezone: Europe/Stockholm

future: true

exclude:
  - TODO.md
  - README.md

defaults:
  -
    scope:
      path: "seminars/"
      type: "posts"
    values:
      layout: seminar
      excerpt_separator: <!--more-->
      permalink: /:categories/:year-:month-:day-:title:output_ext

  -
    scope:
      path: "_pages/lindstrom-lectures/"
      type: "pages"
    values:
      layout: lindstrom-lectures
      permalink: /lindstrom-lectures/:title
      lindstrom-lecture: true

  -
    scope:
      path: ""
      type: "projects"
    values:
      layout: project

collections:
  pages:
    output: true
    permalink: /:path

  static_sites:
    output: true
    permalink: /:path

  events:
    output: true
    
  seminars:
    output: true

  projects:
    output: true

  members:
    order:
      - fredrik.md
      - martin.md
      - rasmus.md
      - bahareh.md
      - graham.md
      - paul.md
    # output: true