title: Logic@GU
author: G.E. Leigh
email: graham.leigh@gu.se
description: > # this means to ignore newlines until "baseurl:"
  Homepage of the Logic Group at the University of Gothenburg.

tagline: The logic group at the University of Gothenburg


baseurl: "/Logic-GU"
# theme: jekyll-theme-slate

future: true

include:
  - _pages

exclude:
  - TODO.md
  - README.md

defaults:
  -
    scope:
      path: ""
      type: "seminars"
    values:
      layout: seminar
      excerpt_separator: <!--more-->

collections:
  seminars:
    output: true

  projects:
    output: true

  members:
    order:
      - fredrik.md
      - martin.md
      - rasmus.md
      - bahareh.md
      - graham.md
      - paul.md
    # output: true